<?php foreach($params['objetos'] as $key => $objeto) { ?>
<tr id="tr<?php echo $objeto->id; ?>">
  <th scope="row">
    <small><?php echo $inicio++; ?></small>
  </th>
  <td>
    <input type="checkbox" name="objetos[]" value="<?php echo $objeto->id; ?>">
  </td>
  <td>
    <a href="?modulo=<?php echo $modulo; ?>&acao=cadastrar&id=<?php echo $objeto->id; ?>"><?php echo $objeto->instituicaoEmpresa; ?></a>
  </td>
  <td class="center">
    <?php 
      $telefones = array();
      if (!empty($objeto->telefone1)) {
        $telefones[] = $objeto->telefone1;
      }
      if (!empty($objeto->telefone2)) {
        $telefones[] = $objeto->telefone2;
      }
      echo '<small>' . implode('<br />', $telefones) . '</small>'; 
    ?>
  </td>
  <td class="tooltp left">
    <span><?php echo Funcoes::compactaTexto($objeto->desconto, 10); ?></span>
    <?php if(!empty($objeto->desconto)) { ?>
    <div class="tip left"><?php echo $objeto->desconto; ?></div>
    <?php } ?>
  </td>
  <td><?php echo $objeto->contato; ?></td>
  <td class="tooltp left">
    <span><?php echo Funcoes::compactaTexto($objeto->email, 10); ?></span>
    <?php if(!empty($objeto->email)) { ?>
    <div class="tip left"><?php echo $objeto->email; ?></div>
    <?php } ?>
  </td>
  <td class="tooltp left">
    <span><?php echo Funcoes::compactaTexto($objeto->observacoes, 10); ?></span>
    <?php if(!empty($objeto->observacoes)) { ?>
    <div class="tip left"><?php echo $objeto->observacoes; ?></div>
    <?php } ?>
  </td>
  <td class="center"><?php echo Funcoes::soData($objeto->data); ?></td>
  <td align="center">
    <a class="excluir-click" target="_self" 
      href="?modulo=<?php echo $modulo; ?>&acao=excluir&id=<?php echo $objeto->id; ?>">Excluir</a>
  </td>
</tr>
<?php } ?>
