<?php
	$params = $this->getParams();
	$objeto = $params["objeto"];
?>

<form method="post" enctype="multipart/form-data">
	<input type="hidden" name="id" value="<?php echo $objeto->id; ?>" />

	<div class="grid">
		<div class="col-1-12">
		   <div class="content">
		   		<label for="Nome"><strong>Nome:</strong></label>
		   </div>
	  	</div>
	  	<div class="col-5-12">
	  	   <div class="content">
	  	   		<input type="text" name="nome" value="<?php echo $objeto->nome; ?>" class="form-control" />
	  	   </div>
	  	</div>
	  	<div class="col-2-12">
		   <div class="content">
		   		<label for="E-mail"><strong>E-mail:</strong></label>
		   </div>
	  	</div>
	  	<div class="col-4-12">
	  	   <div class="content">
	  	   		<input type="text" name="email" value="<?php echo $objeto->email; ?>" class="form-control" />
	  	   </div>
	  	</div>
	</div>

	<div class="grid">
		<div class="col-1-12">
		   <div class="content">
		   		<label for="Nome"><strong>Assunto:</strong></label>
		   </div>
	  	</div>
	  	<div class="col-11-12">
	  	   <div class="content">
	  	   		<input type="text" name="assunto" value="<?php echo $objeto->assunto; ?>" class="form-control" />
	  	   </div>
	  	</div>
	</div>

	<div class="grid">
	  	<div class="col-1-12">
		   <div class="content">
		   		<label for="E-mail"><strong>Cursos:</strong></label>
		   </div>
	  	</div>
	  	<div class="col-11-12">
	  	   <div class="content">
	  	   		<input type="text" name="cursos" value="<?php echo $objeto->cursos; ?>" class="form-control" />
	  	   </div>
	  	</div>
	</div>

	<div class="grid">
		<div class="col-1-12">
		   <div class="content">
		   		<label for="Nome"><strong>Operadora:</strong></label>
		   </div>
	  	</div>
	  	<div class="col-2-12">
	  	   <div class="content">
	  	   		<select id="operadora" name="operadora" class="form-control">
					<option value="">Selecione</option>
					<option value="Claro"<?php if($objeto->operadora == "Claro") echo ' selected="selected"';?>>Claro</option>
					<option value="TIM"<?php if($objeto->operadora == "TIM") echo ' selected="selected"';?>>TIM</option>
					<option value="Vivo"<?php if($objeto->operadora == "Vivo") echo ' selected="selected"';?>>Vivo</option>
				</select>
	  	   </div>
	  	</div>
	  	<div class="col-1-12">
		   <div class="content">
		   		<label for="E-mail"><strong>Telefone:</strong></label>
		   </div>
	  	</div>
	  	<div class="col-2-12">
	  	   <div class="content">
	  	   		<input type="text" name="telefone" value="<?php echo $objeto->telefone; ?>" class="form-control telefone" />
	  	   </div>
	  	</div>
	  	<div class="col-2-12">
		   <div class="content">
		   		<label for="E-mail"><strong>Melhor horário:</strong></label>
		   </div>
	  	</div>
	  	<div class="col-2-12">
	  	   <div class="content">
	  	   		<select id="ligHorario" name="horario" class="form-control">
					<option value="">Selecione</option>
					<option value="Manhã"<?php if($objeto->horario == "Manhã") echo ' selected="selected"';?>>Manhã</option>
					<option value="Tarde">Tarde</option>
					<option value="Noite">Noite</option>
				</select>
	  	   </div>
	  	</div>
	 </div>

	 <div class="grid">
	  	<div class="col-1-12">
		   <div class="content">
		   		<label for="Cidade"><strong>Cidade:</strong></label>
		   </div>
	  	</div>
	  	<div class="col-5-12">
	  	   <div class="content">
	  	   		<input type="text" name="cidade" value="<?php echo $objeto->cidade; ?>" class="form-control" />
	  	   </div>
	  	</div>

		<div class="col-2-12">
		   <div class="content">
		   		<label for="Situação"><strong>Situação:</strong></label>
		   </div>
	  	</div>
	  	<div class="col-4-12">
	  	   <div class="content">
	  	   		<select name="situacao" class="form-control">
	  	   			<option value="">--Selecione--</option>
	  	   			<?php
	  	   				foreach (Ligar::getSituacoes() as $key => $s) {
	  	   					echo '<option';
	  	   					if ($objeto->situacao == $key) {
	  	   						echo ' selected="selected"';
	  	   					}
	  	   					echo ' value="' . $key . '">';
	  	   					echo $s;
	  	   					echo '</option>';
	  	   				}
	  	   			?>
	  	   		</select>
	  	   </div>
	  	</div>
	</div>

	<?php if ($objeto->convertido) { ?>

	<div class="grid">
    	<div class="col-1-12">
    		<div class="content">
    			<label class="tamanho1" for="Convertido?">Convertido?</label>
    		</div>
    	</div>
    	<div class="col-11-12">
    		<div class="content">
    			<select class="form-control" name="curso">
    			    <option value="">--Selecione o curso--</option>
    			    <?php 
    			        foreach ($params['cursos'] as $curso) { 
    			            $option = '<option ';
    			            if ($objeto->curso == $curso->nome) {
    			            	$option .= 'selected ';
    			            }
    			            $option .= 'value="%s">%s</option>';
    			            echo sprintf($option, $curso->nome, $curso->nome);
    			        }
    			    ?>
    			</select>
    		</div>
    	</div>
    </div>

    <?php } ?>

	<div class="grid">
		<div class="col-1-12">
		   <div class="content">
		   		<label for="Observações"><strong>Observ.:</strong></label>
		   </div>
	  	</div>
	  	<div class="col-11-12">
	  	   <div class="content">
	  	   		<textarea rows="10" class="form-control" name="observacoes"><?php echo $objeto->observacoes; ?></textarea>
	  	   </div>
	  	</div>
	</div>
	
	<div class="grid">
		<div class="col-1-12">
		   <div class="content">
		   		&nbsp;
		   </div>
	  	</div>
	  	<div class="col-10-12">
	  	   <div class="content">
	  	   		<input type="submit" class="btn btn-default" value="Salvar"/>
	  	   </div>
	  	</div>
	</div>
</form>