<?php 

  $params = $this->getParams(); 
  $modulo = $_GET['modulo'];
  $quantidadePorPagina = $params['quantidadePorPagina'];
  $exibir = isset($_GET['exibir']) ? $_GET['exibir'] : $quantidadePorPagina;
  $order = isset($_GET['order']) ? $_GET['order'] . ';asc' : 'data;desc';
  $paginacao = $params['paginacao'];
  $quantidade = $params['quantidade'];
  $planilha = $params["columns"];
  $pagina = $params['pagina'];

  if ($quantidade == 0) {
    $iniCount = $inicio = 0;
  }
  else {
    $iniCount = $inicio = ($quantidadePorPagina * $pagina) - ($quantidadePorPagina - 1);
  }
  
  if ($inicio + ($quantidadePorPagina - 1) > $quantidade) {
    $fim = $quantidade;
  }
  else {
    $fim = $inicio + ($quantidadePorPagina - 1);
  }

?>

<style>
  .table {
    font-size: 0.88em;
  }
  ul.pagination {
    margin: 0 !important;
    font-size: 0.85em;
  }
  ul.pagination li a {
      border: 1px solid #ebbc37!important;
      color: #ebbc37;
  }
  ul.pagination li.active span,
  ul.pagination li.active a,
  ul.pagination li a:hover {
      color: #fff !important;
      background-color: #ebbc37 !important;
      border: 1px solid #ebbc37!important;
  }
</style>

<div class="grid">
  <div class="col-2-12">
    <div class="content">
      <small>
        <strong id="inicio">
          <?php if (isset($inicio)) echo $inicio; ?>
        </strong> &rsaquo;
        <strong id="fim">
          <?php if (isset($fim)) echo $fim; ?>
        </strong> de
        <strong id="quantidade">
          <?php if (isset($quantidade)) echo $quantidade; ?>
        </strong> registro(s)
      </small>
    </div>
  </div>
</div>

<?php 
  include 'views/includes/exibir.phtml'; 
  include 'views/includes/planilha-new.phtml'; 
?>

<form method="POST" action="?modulo=<?php echo $modulo; ?>&acao=acoes">

  <!-- Ações -->
  <div class="grid">
    <div class="col-1-12">
      <div class="content">
        <label for="Ações">Ações:</label>
      </div>
    </div>
    <div class="col-5-12">
      <div class="content">
        <select class="form-control" name="acoes">
            <option value="">--Selecione a ação--</option>
            <option value="excluir">Excluir todos</option>
        </select>
      </div>
    </div>
    <div class="col-2-12">
      <div class="content">
        <input class="btn btn-default" type="submit" value="Aplicar" />
      </div>
    </div>
  </div>
  <!-- Ações -->

  <!-- Paginação -->
  <div class="paginacao">
    <?php echo $params['paginacao']; ?>
  </div>
  <!-- Paginação -->

  <!-- Listagem -->
  <div class="grid">
    <div class="col-1-1">
        <div class="content">
          <div class="scroll-pane">
            <table class="table">
              <thead>
                <tr>
                  <th></th>
                  <th class="checkboxes">
                      <input type="checkbox" name="objetos[]" value="-1" onclick="selecionarTodos(this)">
                  </th>
                  <th>
                    <a class="order" href="?modulo=<?php echo $modulo; ?>&order=nome"><strong>Nome</strong></a>
                  </th>
                  <th class="center"><strong>Convertido?</strong></th>
                  <th class="center"><strong>Respondido?</strong></th>
                  <th class="center"><strong>Respondido por</strong></th>
                  <th class="center"><strong>Status</strong></th>
                  <th class="center"><strong>Telefone</strong></th>
                  <th><strong>Mensagem</strong></th>
                  <th><strong>Obs.</strong></th>
                  <th><strong>E-mail</strong></th>
                  <th class="center"><strong>Cidade</strong></th>
                  <th><strong>Estado</strong></th>
                  <th class="center"><strong>Data</strong></th>
                  <th class="acoes" colspan="1"><strong>Ações</strong></th>
                </tr>
              </thead>
              <tbody>
                  <tr id="ajaxTyping" data-modulo="<?php echo $modulo; ?>" 
                    data-order="<?php echo $order; ?>" 
                    data-pagina="<?php echo $pagina; ?>" 
                    data-exibir="<?php echo $quantidadePorPagina; ?>">
                    <td>
                      <img class="keyup-loader hidden" src="imagens/ajax-loader-white-transparent.gif">
                    </td>
                    <td></td>
                    <td>
                      <input class="form-control" type="text" name="nome">
                    </td>
                    <td>
                      <select name="convertido" class="form-control">
                        <option value="">Selecione</option>
                        <option value="1">Sim</option>
                        <option value="0">Não</option>
                      </select>
                    </td>
                    <td>
                      <select name="respondido" class="form-control">
                        <option value="">Selecione</option>
                        <option value="1">Sim</option>
                        <option value="0">Não</option>
                      </select>
                    </td>
                    <td>
                      <input class="form-control" type="text" name="respondidoPor">
                    </td>
                    <td>
                      <select name="status" class="form-control">
                        <option value="">Selecione</option>
                        <?php foreach($params['statuses'] as $key => $value) { ?>
                        <option value="<?php echo $key; ?>"><?php echo $value; ?></option>
                        <?php } ?>
                      </select>
                    </td>
                    <td></td>
                    <td>
                      <input class="form-control" type="text" name="mensagem">
                    </td>
                    <td>
                      <input class="form-control" type="text" name="observacoes">
                    </td>
                    <td>
                      <input class="form-control" type="text" name="email">
                    </td>
                    <td>
                      <input class="form-control" type="text" name="cidade">
                    </td>
                    <td>
                      <input class="form-control" type="text" name="estado">
                    </td>
                    <td>
                      <input class="form-control data" type="text" name="data">
                    </td>
                  </tr>
                  <?php include 'rows.phtml'; ?>
                </tbody>
            </table>
          </div>
        </div>
    </div>
  </div>
  <!-- Listagem -->

  <!-- Paginação -->
  <div class="paginacao">
    <?php echo $params['paginacao']; ?>
  </div>
  <!-- Paginação -->

</form>