<?php
	$params = $this->getParams();
	$cursos = $params["cursos"];
    $contato = $params["contato"];
?>

<form method="POST">
    <div class="grid">
        <div class="col-1-12">
            <div class="content">
                <label class="tamanho1" for="Nome">Nome:</label>
            </div>
        </div>
        <div class="col-7-12">
            <div class="content">
                <?php echo $contato->nome; ?>
            </div>
        </div>
    </div>
    <div class="grid">
        <div class="col-1-12">
            <div class="content">
                <label class="tamanho1" for="Status">Status:</label>
            </div>
        </div>
        <div class="col-4-12">
            <div class="content">
                <select name="status" class="form-control">
                <?php 
                    foreach ($params['statuses'] as $key => $value) {
                        echo '<option value="' . $key . '">' . $value . '</option>';
                    } 
                ?>
                </select>
            </div>
        </div>
    </div>
    <div class="grid">
    	<div class="col-1-12">
    		<div class="content">
    			<label class="tamanho1" for="Curso">Curso:</label>
    		</div>
    	</div>
    	<div class="col-7-12">
    		<div class="content">
    			<select class="form-control" name="curso">
    			    <option value="">--Selecione o curso--</option>
    			    <?php 
    			        foreach ($cursos as $curso) { 
    			            echo '<option value="' . $curso->id . '">' . $curso->nome . '</option>';
    			        }
    			    ?>
    			</select>
    		</div>
    	</div>
    </div>
    <div class="grid">
        <div class="col-1-12">
            <div class="content">&nbsp;</div>
        </div>
    	<div class="col-1-12">
    		<div class="content">
    			<input class="btn btn-default" type="submit" value="Ok" />
    		</div>
    	</div>
    </div>
</form>