<?php
	$params = $this->getParams();
	$contato = $params["contato"];
?>

<form method="post" enctype="multipart/form-data">
	<input type="hidden" name="id" value="<?php echo $contato->id; ?>" />
	<div class="grid">
		<div class="col-1-12">
		   <div class="content">
		   		<label for="Observações"><strong>Observações:</strong></label>
		   </div>
	  	</div>
	  	<div class="col-11-12">
	  	   <div class="content">
	  	   		<textarea rows="10" class="form-control" name="observacoes"><?php echo $contato->observacoes; ?></textarea>
	  	   </div>
	  	</div>
	</div>
	
	<div class="grid">
		<div class="col-1-12">
		   <div class="content">
		   		&nbsp;
		   </div>
	  	</div>
	  	<div class="col-10-12">
	  	   <div class="content">
	  	   		<input type="submit" class="btn btn-default" value="Salvar"/>
	  	   </div>
	  	</div>
	</div>
</form>