<?php foreach($params['objetos'] as $key => $objeto) { ?>
<tr id="tr<?php echo $objeto->id; ?>">
  <th scope="row">
    <small><?php echo $inicio++; ?></small>
  </th>
  <td>
    <input type="checkbox" name="objetos[]" value="<?php echo $objeto->id; ?>">
  </td>
  <td>
    <a href="?modulo=<?php echo $modulo; ?>&acao=responder&id=<?php echo $objeto->id; ?>"><?php echo $objeto->nome; ?></a><br />
  </td>
  <?php 
    $classes = array();
    $classes[] = 'center';
    if ($objeto->convertido) {
      $classes[] = 'tooltp right';
    }
  ?>
  <td class="<?php echo implode(' ', $classes); ?>"><?php 
      if ($objeto->convertido) {
        echo '<span>Sim</span>';
        echo '<div class="tip right">' . $objeto->curso . '</div>';
      } 
      else {
        echo 'Não'; 
      }?></td>
  <td class="center"><?php echo $objeto->respondido ? 'Sim' : 'Não'; ?></td>
  <?php 
    $classes = array();
    $classes[] = 'center';
    if ($objeto->respondido) {
      $classes[] = 'tooltp right';
    }
  ?>
  <td class="<?php echo implode(' ', $classes); ?>"><?php 
      if ($objeto->respondido) {
        echo '<span>' . $objeto->respondidoPor . '</span>';
        echo '<div class="tip right"> Respondido em ' . $objeto->dataResposta . '</div>';
      } ?></td>
  <td class="center"><?php echo Contato::getStatus($objeto->status); ?></td>
  <td class="center"><?php echo $objeto->assunto; ?></td>
  <td><?php echo $objeto->telefone; ?></td>
  <td class="tooltp left">
    <span><?php echo Funcoes::compactaTexto($objeto->mensagem, 10); ?></span>
    <?php if(!empty($objeto->mensagem)) { ?>
    <div class="tip left"><?php echo $objeto->mensagem; ?></div>
    <?php } ?>
  </td>
  <td class="tooltp left">
    <span><?php echo Funcoes::compactaTexto($objeto->cursos, 10); ?></span>
    <?php if(!empty($objeto->cursos)) { ?>
    <div class="tip left"><?php echo $objeto->cursos; ?></div>
    <?php } ?>
  </td>
  <td class="tooltp left">
    <span><?php echo Funcoes::compactaTexto($objeto->observacoes, 10); ?></span>
    <?php if(!empty($objeto->observacoes)) { ?>
    <div class="tip left"><?php echo $objeto->observacoes; ?></div>
    <?php } ?>
  </td>
  <td><?php echo $objeto->email; ?></td>
  <td class="center"><?php echo $objeto->cidade; ?></td>
  <td class="center"><?php echo $objeto->estado; ?></td>
  <td class="center"><?php echo Funcoes::soData($objeto->data); ?></td>
  <td align="center">
    <a class="excluir-click" target="_self" 
      href="?modulo=<?php echo $modulo; ?>&acao=excluir&id=<?php echo $objeto->id; ?>">Excluir</a>
  </td>
</tr>
<tr class="links">
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td colspan="12">
    <div id="links">
      <a target="_self" href="?modulo=<?php echo $modulo; ?>&acao=responder&id=<?php echo $objeto->id; ?>">Responder</a>
      | 
      <a target="_self" href="?modulo=<?php echo $modulo; ?>&acao=observacoes&id=<?php echo $objeto->id; ?>">Observações</a> 
      | 
      <a target="_self" href="?modulo=<?php echo $modulo; ?>&acao=status&id=<?php echo $objeto->id; ?>">Status</a> 
      <?php if (!$objeto->convertido) { ?>
      | 
      <a target="_self" href="?modulo=<?php echo $modulo; ?>&acao=nova&id=<?php echo $objeto->id; ?>">Converter para inscrição</a>
      <?php } ?>
    </div>
  </td>
</tr>
<?php } ?>
