<?php
	$params = $this->getParams();
	$usuario = $params["usuario"];
?>

<form method="post">

<input type="hidden" name="id" value="<?php echo $usuario->id; ?>" />
    
<div class="grid">
	<div class="col-2-12">
	   <div class="content">
	   		<label for="Nome">Nome:</label>
	   </div>
  	</div>
	<div class="col-10-12">
		<div class="content">
			<input class="form-control" name="nome" type="text" value="<?php echo $usuario->nome; ?>" autofocus="autofocus" />
		</div>
	</div>
</div>

<div class="grid">
	<div class="col-2-12">
	   <div class="content">
	   		<label for="Login">Login:</label>
	   </div>
  	</div>
	<div class="col-4-12">
		<div class="content">
			<input class="form-control" name="login" type="text" value="<?php echo $usuario->login; ?>" />
		</div>
	</div>
	<div class="col-2-12">
	   <div class="content">
	   		<label for="E-mail">E-mail:</label>
	   </div>
		</div>
	<div class="col-4-12">
		<div class="content">
			<input class="form-control" name="email" type="text" value="<?php echo $usuario->email; ?>" />
		</div>
	</div>
</div>

<div class="grid">
	<div class="col-2-12">
	   <div class="content">
	   		<label for="Senha Atual">Senha Atual:</label>
	   </div>
		</div>
	<div class="col-4-12">
		<div class="content">
			<input class="form-control" name="senhaAtual" type="password" />
		</div>
	</div>
	<div class="col-2-12">
	   <div class="content">
	   		<label for="Nova Senha">Nova Senha:</label>
	   </div>
		</div>
	<div class="col-4-12">
		<div class="content">
			<input class="form-control" name="novaSenha" type="password" />
		</div>
	</div>
</div>

<input class="btn btn-default" type="submit" value="Salvar" /> 

</form>