<form method="GET">
  <div class="grid">
    <div class="col-1-12">
      <div class="content">
        <label for="Exibir">Exibir:</label>
      </div>
    </div>
    <div class="col-1-12">
      <div class="content">
        <?php
          foreach ($_GET as $key => $value) {
            if (!in_array($key, array("exibir", "p"))) {
                echo '<input type="hidden" name="' . $key . '" value="' . $value . '"/>';
              }
          }
        ?>
        <input id="exibir" class="form-control" size="10" type="text" name="exibir" value="<?php if (isset($_GET["exibir"])) echo $_GET["exibir"]; ?>" />
      </div>
    </div>
    <div class="col-2-12">
      <div class="content">
        <input class="btn btn-default" type="submit" value="Ok" />
      </div>
    </div>
  </div>
</form>