<?php if (isset($planilha)) { ?>

<form id="planilha" method="POST" action="?modulo=<?php echo $_GET['modulo']; ?>&acao=planilha<?php if (isset($_GET['order'])) echo '&order=' . $_GET['order'];?>">
  <div class="grid">
    <div class="col-1-12">
      <div class="content">
        <label for="Planilha">Planilha:</label>
      </div>
    </div>
    <div class="col-10-12">
      <div class="content">
        <?php
          foreach ($_GET as $key => $value) {
            if (!in_array($key, array("modulo", "acao"))) {
              echo '<input type="hidden" name="' . $key . '" value="' . $value . '"/>';
            }
          }
        ?>
        <fieldset id="planilha">
          <label class="checkbox-inline">
            <input name="colunas[]" type="checkbox" id="tudo" onclick="marcarDesmarcar(this, 'planilha')" value="-1" /> <small>Tudo</small>
          </label>
          <?php
            foreach ($planilha as $key => $info) {
              if ($info['planilha']) {
                echo '<label class="checkbox-inline">';
                echo '<input name="colunas[]" type="checkbox" value="' . $key . '" /> <small>' . ucfirst($info['name']);
                echo '</small></label>';
              }
            }
          ?>
        </fieldset>
      </div>
    </div>
    <div class="col-1-12">
      <div class="content">
        <input class="btn btn-default" type="submit" value="Ok" />
      </div>
    </div>
  </div>
</form>

<?php } ?>