<?php
	$params = $this->getParams();
	$permissao = $params["objeto"];
?>

<form method="post" enctype="multipart/form-data">

	<input type="hidden" name="id" value="<?php echo $permissao->id; ?>" />
	
	<div class="grid">
		<div class="col-1-12">
		   <div class="content">
		   		<label for="Permissão">Permissão:</label>
		   </div>
	  	</div>
		<div class="col-11-12">
			<div class="content">
				<input class="form-control" name="nome" type="text" value="<?php echo $permissao->nome; ?>" size="60" autofocus placeholder="Permissão"/>
			</div>
		</div>
	</div>
	
	<div class="grid">
		<div class="col-1-12">
		   <div class="content">
		   		&nbsp;
		   </div>
	  	</div>
		<div class="col-11-12">
			<div class="content">
				<input class="btn btn-default" type="submit" value="Salvar" />
			</div>
		</div>
	</div>

</form>

