<?php
	$params = $this->getParams();
	$objeto = $params["objeto"];
?>
<form method="post">
    
    <div class="grid">
    	<div class="col-1-12">
    		<div class="content">
    			<label for="De">De:</label>
    		</div>
    	</div>
    	<div class="col-6-12">
    		<div class="content">
    			<input class="form-control" name="de" type="text" value="cursos@iefap.com.br" size="50"/>
    		</div>
    	</div>
    </div>
    
    <div class="grid">
    	<div class="col-1-12">
    		<div class="content">
    			<label for="Para">Para:</label>
    		</div>
    	</div>
    	<div class="col-6-12">
    		<div class="content">
    			<input class="form-control" name="email" type="text" value="<?php echo $objeto["email"]; ?>" size="50"/>
    		</div>
    	</div>
    </div>
    
    <div class="grid">
    	<div class="col-1-12">
    		<div class="content">
    			<label for="E-mail">E-mail:</label>
    		</div>
    	</div>
    	<div class="col-11-12">
    		<div class="content">
    			<textarea class="ckeditor" name="resposta"></textarea>
    		</div>
    	</div>
    </div>
    
    <div class="grid">
    	<div class="col-1-12">
    		<div class="content">
    			&nbsp;
    		</div>
    	</div>
    	<div class="col-11-12">
    		<div class="content">
    			<input type="submit" class="btn btn-default" value="Enviar" />
    		</div>
    	</div>
    </div>
    
    
</form>

