<?php
	$params = $this->getParams();
	$preinscricao = $params["preinscricao"];
	$cursos = $params["cursos"];
?>

<form method="post">
	
    <input type="hidden" name="id" value="<?php echo $preinscricao["id"]; ?>" />
    
    <div class="grid">
    	<div class="col-1-12">
    		<div class="content">
    			<label for="Curso">Curso:</label>
    		</div>
    	</div>
    	<div class="col-8-12">
    		<div class="content">
    			<select class="form-control" name="curso">
    			    <option value="">--Selecione o curso--</option>
    			    <?php 
    			        foreach ($cursos as $curso) { 
    			            echo '<option value="'.$curso["id"].'">'.$curso["nome"].'</option>';
    			        }
    			    ?>
    			</select>
    		</div>
    	</div>
    </div>
    
    <div class="grid">
    	<div class="col-1-12">
    		<div class="content">
    			&nbsp;
    		</div>
    	</div>
    	<div class="col-8-12">
    		<div class="content">
    			<input class="btn btn-default" type="submit" value="Mudar" />
    		</div>
    	</div>
    </div>
    
</form>