<?php
  $params = $this->getParams();
  $modulo = $_GET["modulo"];
  $exibir = isset($_GET["exibir"]) ? $_GET["exibir"] : NULL;
  $order = isset($_GET["order"]) ? $_GET["order"] : NULL;
    $quantidade = $params["quantidade"];
    $quantidadePorPagina = $params["quantidadePorPagina"];
    $pagina = $params["pagina"];
    
    if ($quantidade == 0) {
        $iniCount = $inicio = 0;
    }
    else {
        $iniCount = $inicio = ($quantidadePorPagina * $pagina) - ($quantidadePorPagina - 1);
    }
    
    if ($inicio + ($quantidadePorPagina - 1) > $quantidade) {
        $fim = $quantidade;
    }
    else {
        $fim = $inicio + ($quantidadePorPagina - 1);
    }
    
    include('list-index.phtml');
    
    echo '<div class="grid top-items">';
    echo '<div class="col-1-1">';
    echo '<div class="content">';
    
    echo '<a href="?modulo=index&acao=nova">';
    echo '<div class="item">';
    echo '<span class="ti-save"></span>';
    echo '<span class="icon-name">';
    echo 'Nova';
    echo '</span>';
    echo '</div>';
    echo '</a>';
    
    if (checaPermissao($modulo, 'filtro', $_SESSION[PREFIX . "permissoes"])) {
      echo '<a href="?modulo=' . $modulo . '&acao=filtro">';
      echo '<div class="item">';
      echo '<span class="ti-filter"></span>';
      echo '<span class="icon-name">';
      echo 'Filtrar';
      echo '</span>';
      echo '</div>';
      echo '</a>';
    }
      
    echo '</div></div></div>';
        
    include('views/includes/listagem.phtml'); 
        
?>