<?php
	$params = $this->getParams();
	$cursos = $params["cursos"];
?>

<form method="POST">
    <div class="grid">
    	<div class="col-1-12">
    		<div class="content">
    			<label class="tamanho1" for="Curso">Curso:</label>
    		</div>
    	</div>
    	<div class="col-10-12">
    		<div class="content">
    			<select class="form-control" name="curso">
    			    <option value="">--Selecione o curso--</option>
    			    <?php 
    			        foreach ($cursos as $curso) { 
    			            echo '<option value="'.$curso["id"].'">'.$curso["nome"].'</option>';
    			        }
    			    ?>
    			</select>
    		</div>
    	</div>
    	<div class="col-1-12">
    		<div class="content">
    			<input class="btn btn-default" type="submit" value="Ok" />
    		</div>
    	</div>
    </div>
</form>