<?php 

  $params = $this->getParams(); 
  $modulo = $_GET['modulo'];
  $quantidadePorPagina = $params['quantidadePorPagina'];
  $exibir = isset($_GET['exibir']) ? $_GET['exibir'] : $quantidadePorPagina;
  $order = isset($_GET['order']) ? $_GET['order'] . ';asc' : 'data;desc';
  $paginacao = $params['paginacao'];
  $quantidade = $params['quantidade'];
  $pagina = $params['pagina'];

  if ($quantidade == 0) {
    $iniCount = $inicio = 0;
  }
  else {
    $iniCount = $inicio = ($quantidadePorPagina * $pagina) - ($quantidadePorPagina - 1);
  }
  
  if ($inicio + ($quantidadePorPagina - 1) > $quantidade) {
    $fim = $quantidade;
  }
  else {
    $fim = $inicio + ($quantidadePorPagina - 1);
  }

?>

<style>
  .table {
    font-size: 0.88em;
  }
  ul.pagination {
    margin: 0 !important;
    font-size: 0.85em;
  }
  ul.pagination li a {
      border: 1px solid #ebbc37!important;
      color: #ebbc37;
  }
  ul.pagination li.active span,
  ul.pagination li.active a,
  ul.pagination li a:hover {
      color: #fff !important;
      background-color: #ebbc37 !important;
      border: 1px solid #ebbc37!important;
  }
</style>

<div class="grid top-items">
  <div class="col-1-1">
    <div class="content">
      <a href="?modulo=<?php echo $modulo; ?>&acao=cadastrar">
        <div class="item">
          <span class="ti-save"></span>
          <span class="icon-name">Novo</span>
        </div>
      </a>
    </div>
  </div>
</div>

<div class="grid">
  <div class="col-2-12">
    <div class="content">
      <small>
        <strong id="inicio">
          <?php if (isset($inicio)) echo $inicio; ?>
        </strong> &rsaquo;
        <strong id="fim">
          <?php if (isset($fim)) echo $fim; ?>
        </strong> de
        <strong id="quantidade">
          <?php if (isset($quantidade)) echo $quantidade; ?>
        </strong> registro(s)
      </small>
    </div>
  </div>
</div>

<?php 
  include 'views/includes/exibir.phtml'; 
?>

<form method="POST" action="?modulo=<?php echo $modulo; ?>&acao=acoes">

  <!-- Ações -->
  <div class="grid">
    <div class="col-1-12">
      <div class="content">
        <label for="Ações">Ações:</label>
      </div>
    </div>
    <div class="col-5-12">
      <div class="content">
        <select class="form-control" name="acoes">
            <option value="">--Selecione a ação--</option>
            <option value="excluir">Excluir todos</option>
        </select>
      </div>
    </div>
    <div class="col-2-12">
      <div class="content">
        <input class="btn btn-default" type="submit" value="Aplicar" />
      </div>
    </div>
  </div>
  <!-- Ações -->

  <!-- Paginação -->
  <div class="paginacao">
    <?php echo $params['paginacao']; ?>
  </div>
  <!-- Paginação -->

  <!-- Listagem -->
  <div class="grid">
    <div class="col-1-1">
        <div class="content">
          <table class="table">
            <thead>
              <tr>
                <th></th>
                <th class="checkboxes">
                    <input type="checkbox" name="objetos[]" value="-1" onclick="selecionarTodos(this)">
                </th>
                <th>
                  <a class="order" href="?modulo=<?php echo $modulo; ?>&order=nome"><strong>Nome</strong></a>
                </th>
                <th class="center"><strong>Situação</strong></th>
                <th class="center"><strong>Titulação</strong></th>
                <th class="center"><strong>Currículo?</strong></th>
                <th class="center"><strong>Cidade</strong></th>
                <th class="center"><strong>Estado</strong></th>
                <th class="center"><strong>Graduações</strong></th>
                <th class="center"><strong>Cursos</strong></th>
                <th class="center"><strong>Disciplinas</strong></th>
                <th class="center"><strong>Telefone(s)</strong></th>
                <th class="center"><strong>E-mail</strong></th>
                <th class="center"><strong>Data</strong></th>
                <th class="acoes" colspan="1"><strong>Ações</strong></th>
              </tr>
            </thead>
            <tbody>
                <tr id="ajaxTyping" data-modulo="<?php echo $modulo; ?>" 
                  data-order="<?php echo $order; ?>" 
                  data-pagina="<?php echo $pagina; ?>" 
                  data-exibir="<?php echo $quantidadePorPagina; ?>">
                  <td>
                    <img class="keyup-loader hidden" src="imagens/ajax-loader-white-transparent.gif">
                  </td>
                  <td></td>
                  <td>
                    <input class="form-control" type="text" name="nome">
                  </td>
                  <td>
                    <select class="form-control" name="situacao">
                      <option value="">--Selecione--</option>
                      <?php
                        foreach (Docente::getSituacoes() as $key => $value) {
                          echo '<option value="' . $key . '">' . $value . '</option>';
                        }
                      ?>
                    </select>
                  </td>
                  <td>
                    <select class="form-control" name="titulacao">
                      <option value="">--Selecione--</option>
                      <?php
                        foreach (Docente::getTitulacoes() as $key => $value) {
                          echo '<option value="' . $key . '">' . $value . '</option>';
                        }
                      ?>
                    </select>
                  </td>
                  <td></td>
                  <td>
                    <input class="form-control" type="text" name="cidade">
                  </td>
                  <td>
                    <select class="form-control" name="uf">
                      <option value="">--Selecione--</option>
                      <option value="AC">AC</option>
                      <option value="AL">AL</option>
                      <option value="AP">AP</option>
                      <option value="AM">AM</option>
                      <option value="BA">BA</option>
                      <option value="CE">CE</option>
                      <option value="DF">DF</option>
                      <option value="ES">ES</option>
                      <option value="GO">GO</option>
                      <option value="MA">MA</option>
                      <option value="MT">MT</option>
                      <option value="MS">MS</option>
                      <option value="MG">MG</option>
                      <option value="PA">PA</option>
                      <option value="PB">PB</option>
                      <option value="PR">PR</option>
                      <option value="PE">PE</option>
                      <option value="PI">PI</option>
                      <option value="RJ">RJ</option>
                      <option value="RN">RN</option>
                      <option value="RS">RS</option>
                      <option value="RO">RO</option>
                      <option value="RR">RR</option>
                      <option value="SC">SC</option>
                      <option value="SP">SP</option>
                      <option value="SE">SE</option>
                      <option value="TO">TO</option>
                    </select>
                  </td>
                  <td>
                    <input class="form-control" type="text" name="graduacoes">
                  </td>
                  <td>
                    <input class="form-control" type="text" name="curso">
                  </td>
                  <td>
                    <input class="form-control" type="text" name="disciplinas">
                  </td>
                  <td></td>
                  <td>
                    <input class="form-control" type="text" name="email">
                  </td>
                  <td>
                    <input class="form-control data" type="text" name="data">
                  </td>
                </tr>
                <?php include 'rows.phtml'; ?>
              </tbody>
          </table>
        </div>
    </div>
  </div>
  <!-- Listagem -->

  <!-- Paginação -->
  <div class="paginacao">
    <?php echo $params['paginacao']; ?>
  </div>
  <!-- Paginação -->

</form>