<?php
    $params = $this->getParams();
    $objeto = $params["objeto"];
?>

<form method="post" enctype="multipart/form-data">

    <input type="hidden" name="id" value="<?php echo $objeto->id; ?>" />
    
    <?php if ($objeto->id == 0) { ?>
    <div class="grid">
        <div class="col-1-12">
           <div class="content">
                <label for="Categoria">Página:</label>
           </div>
        </div>
        <div class="col-4-12">
            <div class="content">
                <select class="form-control" name="pagina" id="pagina">
                    <option value="">--Selecione--</option>
                    <?php
                        foreach ($params["paginas"] as $key => $value) {
                            echo '<option ';
                            if ($objeto->pagina == $key) {
                                echo 'selected="selected" ';
                            }
                            echo 'value="' . $key . '">' . $value . '</option>';
                        }
                    ?>
                </select>
            </div>
        </div>
    </div>
    <?php } else { ?>
        <input type="hidden" name="pagina" value="<?php echo $objeto->pagina; ?>" />
    <?php } ?>
    
    
    <div class="grid">
        <div class="col-1-12">
           <div class="content">
                <label for="Título">Título:</label>
           </div>
        </div>
        <div class="col-11-12">
            <div class="content">
                <input class="form-control" id="titulo" name="titulo" type="text" value="<?php echo $objeto->titulo; ?>" size="60" autofocus="autofocus" placeholder="Título da Página"/>
            </div>
        </div>
    </div>
    
    <div class="grid">
        <div class="col-1-12">
           <div class="content">
                <label for="Conteúdo">Conteúdo:</label>
           </div>
        </div>
        <div class="col-11-12">
            <div class="content">
                <textarea class="editor" data-toolbar="basic" name="conteudo" id="conteudo"><?php echo $objeto->conteudo; ?></textarea>
            </div>
        </div>
    </div>

    <?php if ($objeto->id > 0) { ?>

    <div class="grid">
        <div class="col-1-12">
           <div class="content">&nbsp;</div>
        </div>
        <div class="col-11-12">
            <div class="content">
                <p class="small">Cadastrada em <?php echo $objeto->data; ?></p>
            </div>
        </div>
    </div>

    <?php } ?>
    
    <div class="grid">
        <div class="col-1-12">
           <div class="content">
                &nbsp;         
            </div>
        </div>
        <div class="col-9-12">
            <div class="content">
                <input class="btn btn-default" type="submit" value="Salvar">
            </div>
        </div>
    </div>
</form>

<script>
    $("#pagina").on('change', function () {
        $("#titulo").val($(this).find('option:selected').text());
    });
</script>