<?php foreach($params['objetos'] as $key => $objeto) { ?>
<tr id="tr<?php echo $objeto->id; ?>">
  <th scope="row">
    <small><?php echo $inicio++; ?></small>
  </th>
  <td>
    <input type="checkbox" name="objetos[]" value="<?php echo $objeto->id; ?>">
  </td>
  <td>
    <a href="?modulo=<?php echo $modulo; ?>&acao=cadastrar&id=<?php echo $objeto->id; ?>"><?php echo $objeto->nome; ?></a><br />
  </td>
  <td><?php echo $objeto->email; ?></td>
  <td class="center"><?php echo $objeto->cidade; ?></td>
  <td class="center"><?php echo $objeto->uf; ?></td>
  <td class="tooltp left">
    <span><?php echo Funcoes::compactaTexto($objeto->observacoes, 10); ?></span>
    <?php if(!empty($objeto->observacoes)) { ?>
    <div class="tip left"><?php echo $objeto->observacoes; ?></div>
    <?php } ?>
  </td>
  <td class="center"><?php echo $objeto->endereco; ?></td>
  <td class="center"><?php echo Funcoes::soData($objeto->data); ?></td>
  <td align="center">
    <a class="excluir-click" target="_self" 
      href="?modulo=<?php echo $modulo; ?>&acao=excluir&id=<?php echo $objeto->id; ?>">Excluir</a>
  </td>
</tr>
<tr class="links">
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td colspan="12">
    <div id="links">
      <a target="_self" href="?modulo=<?php echo $modulo; ?>&acao=nova&id=<?php echo $objeto->id; ?>">Converter para inscrição</a>
    </div>
  </td>
</tr>
<?php } ?>
