<?php
	$params = $this->getParams();
    $cursos = $params["cursos"];
?>

<form method="post">
	
	<div class="grid">
		<div class="col-1-12">
		   <div class="content">
		   		<label for="Curso">Curso:</label>
		   </div>
	  	</div>
		<div class="col-10-12">
			<div class="content">
				<select class="form-control" name="curso">
					<option value="">--Selecione o curso--</option>
					<?php	
						foreach ($params["cursos"] as $curso) {
							echo '<option';
							echo ' value="' . $curso->id . '"';
							echo '>';
							echo $curso->nome;
							echo '</option>';
						}
					?>
				</select>
			</div>
		</div>
	</div>
	
	<div class="grid">
		<div class="col-1-12">
		   <div class="content">
		   		&nbsp;		   
		   	</div>
	  	</div>
		<div class="col-9-12">
			<div class="content">
				<input class="btn btn-default" type="submit" value="Gerar" />
			</div>
		</div>
	</div>

</form>