<?php
	$params = $this->getParams();
	$curso = $params["objeto"];
?>

<form method="post">

	<input type="hidden" name="id" value="<?php echo $curso->id; ?>" />

	<div class="grid">
		<div class="col-1-12">
		   <div class="content">
		   		<label for="Tipo">Tipo:</label>
		   </div>
	  	</div>
		<div class="col-3-12">
			<div class="content">
				<select class="form-control" name="tipo">
					<option value="">--Selecione--</option>
					<?php
						foreach (Curso::getTipos() as $key => $value) {
							echo '<option';
							if ($curso->tipo == $key) {
								echo ' selected';
							}
							echo ' value="' . $key . '">' . $value . '</option>';
						}
					?>
				</select>
			</div>
		</div>
	</div>
	
	<div class="grid">
		<div class="col-1-12">
		   <div class="content">
		   		&nbsp;		   </div>
	  	</div>
		<div class="col-9-12">
			<div class="content">
				<input class="btn btn-default" type="submit" value="Mudar" />
			</div>
		</div>
	</div>

</form>