<?php foreach($params['objetos'] as $key => $objeto) { ?>
<tr id="tr<?php echo $objeto->id; ?>">
  <th scope="row">
    <small><?php echo $inicio++; ?></small>
  </th>
  <td>
    <input type="checkbox" name="objetos[]" value="<?php echo $objeto->id; ?>">
  </td>
  <td>
    <a<?php if ($objeto->status == 0) echo ' class="desativada"'; ?> href="?modulo=<?php echo $modulo; ?>&acao=cadastrar&tipo=<?php echo $objeto->tipo; ?>&id=<?php echo $objeto->id; ?>"><?php echo $objeto->nome; ?></a>
  </td>
  <td class="center"><?php echo Curso::getCertificadora($objeto->unidadeCertificadora); ?></td>
  <td class="center"><?php echo Curso::getTipo($objeto->tipo); ?></td>
  <td class="center"><?php echo $objeto->nomeCategoria; ?></td>
  <td class="center"><?php echo Curso::getArea($objeto->area); ?></td>
  <td class="center"><?php echo Funcoes::soData($objeto->data); ?></td>
  <td align="center">
    <a class="excluir-click" target="_self" 
      href="?modulo=<?php echo $modulo; ?>&acao=excluir1&id=<?php echo $objeto->id; ?>">Excluir</a>
  </td>
</tr>
<tr class="links">
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td colspan="12">
    <div id="links">
      <a target="_self" href="<?php echo WWW_ROOT; ?>/curso/<?php echo $objeto->link; ?>">Visualizar</a> |
      <a target="_self" href="?modulo=<?php echo $modulo; ?>&acao=tipo&id=<?php echo $objeto->id; ?>">Mudar tipo</a> | 
      <a target="_self" href="?modulo=<?php echo $modulo; ?>&acao=imagens&id=<?php echo $objeto->id; ?>">Imagens</a>
    </div>
  </td>
</tr>
<?php } ?>
