<?php foreach($params['objetos'] as $key => $objeto) { ?>
<tr id="tr<?php echo $objeto->id; ?>">
  <th scope="row">
    <small><?php echo $inicio++; ?></small>
  </th>
  <td>
    <input type="checkbox" name="objetos[]" value="<?php echo $objeto->id; ?>">
  </td>
  <td>
    <a href="?modulo=<?php echo $modulo; ?>&acao=cadastrar&id=<?php echo $objeto->id; ?>"><?php echo $objeto->nome; ?></a>
  </td>
  <td class="center"><?php echo !empty($objeto->curriculoComercial) ? 'Sim' : 'Não'; ?></td>
  <td class="center"><?php echo $objeto->cidade; ?></td>
  <td class="center"><?php echo $objeto->uf; ?></td>
  <td class="center">
    <?php 
      $telefones = array();
      if (!empty($objeto->telefoneResidencial)) {
        $telefones[] = $objeto->telefoneResidencial;
      }
      if (!empty($objeto->telefoneCelular)) {
        $telefones[] = $objeto->telefoneCelular;
      }
      echo '<small>' . implode('<br />', $telefones) . '</small>'; 
    ?>
  </td>
  <td><?php echo $objeto->email; ?></td>
  <td class="center"><?php echo Funcoes::soData($objeto->data); ?></td>
  <td align="center">
    <a class="excluir-click" target="_self" 
      href="?modulo=<?php echo $modulo; ?>&acao=excluir&id=<?php echo $objeto->id; ?>">Excluir</a>
  </td>
</tr>
<tr class="links">
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td colspan="12">
    <div id="links">
      <a target="_self" href="?modulo=<?php echo $modulo; ?>&acao=email&id=<?php echo $objeto->id; ?>">E-mail</a>
    </div>
  </td>
</tr>
<?php } ?>
