<?php 

  $params = $this->getParams(); 
  $modulo = $_GET['modulo'];
  $order = isset($_GET['order']) ? $_GET['order'] . ';asc' : 'nome;asc';

?>

<style>
  ul.pagination {
    margin: 0 !important;
    font-size: 0.85em;
  }
  ul.pagination li a {
      border: 1px solid #ebbc37!important;
      color: #ebbc37;
  }
  ul.pagination li.active span,
  ul.pagination li.active a,
  ul.pagination li a:hover {
      color: #fff !important;
      background-color: #ebbc37 !important;
      border: 1px solid #ebbc37!important;
  }
</style>

<div class="grid">
  <div class="col-2-12">
    <div class="content">
      <small>
        <strong id="inicio"><?php echo count($params['objetos']) > 0 ? 1 : 0;?></strong> &rsaquo;
        <strong id="fim"><?php echo count($params['objetos']); ?></strong> de
        <strong id="quantidade"><?php echo count($params['objetos']); ?></strong> registro(s)
      </small>
    </div>
  </div>
</div>

<!-- Listagem -->
<div class="grid">
  <div class="col-1-1">
      <div class="content">
        <table class="table">
          <thead>
            <tr>
              <th></th>
              <th><strong>Estado</strong></th>
              <th><strong>Região</strong></th>
            </tr>
          </thead>
          <tbody>
              <tr id="ajaxTyping" data-action="ajax1" data-modulo="<?php echo $modulo; ?>" 
                data-order="<?php echo $order; ?>">
                <td>
                  <img class="keyup-loader hidden" src="imagens/ajax-loader-white-transparent.gif">
                </td>
                <td>
                  <input class="form-control" type="text" name="nome">
                </td>
                <td>
                  <select class="form-control" name="regiao">
                      <option value="">--Selecione--</option>
                      <?php foreach ($params['regioes'] as $regiao) { ?>
                      <option value="<?php echo $regiao->id; ?>"><?php echo $regiao->nome; ?></option>
                      <?php } ?>
                    </select>
                </td>
              </tr>
              <?php include 'rows-estados.phtml'; ?>
            </tbody>
        </table>
      </div>
  </div>
</div>
<!-- Listagem -->