<?php foreach($params['objetos'] as $key => $objeto) { ?>
<tr id="tr<?php echo $objeto->id; ?>">
  <th scope="row">
    <small><?php echo ++$key; ?></small>
  </th>
  <td>
    <input type="checkbox" name="objetos[]" value="<?php echo $objeto->id; ?>">
  </td>
  <td>
    <a href="?modulo=<?php echo $modulo; ?>&acao=cadastrar&id=<?php echo $objeto->id; ?>&estado=<?php echo $objeto->idEstado; ?>"><?php echo $objeto->nome; ?></a><br />
    <small><?php echo $objeto->quantidadeCursos; ?> curso(s)</small>
  </td>
  <td class="center"><?php echo $objeto->emails; ?></td>
  <td class="center"><?php echo Funcoes::soData($objeto->data); ?></td>
  <td class="center">
    <a class="excluir-click" target="_self" 
      href="?modulo=<?php echo $modulo; ?>&acao=excluir&id=<?php echo $objeto->id; ?>">Excluir</a>
  </td>
</tr>
<tr class="links">
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td colspan="2">
    <div id="links">
      <a target="_self" href="?modulo=<?php echo $modulo; ?>&acao=associar&cidade=<?php echo $objeto->id; ?>&estado=<?php echo $objeto->idEstado; ?>">Associar cursos</a>
    </div>
  </td>
</tr>
<?php } ?>
