<?php
	$params = $this->getParams();
	$usuario = $params['objeto'];
?>

<form method="post">

	<input type="hidden" name="id" value="<?php echo $usuario->id; ?>" />
	    
	<div class="grid">
    	<div class="col-1-12">
    		<div class="content">
    			&nbsp;
    		</div>
    	</div>
		<div class="col-11-12">
		   <div class="content">
		   		<input type="hidden" name="status" value="0" />
		   		<div class="checkbox">
			   		<label>
						<input type="checkbox" name="status" value="1" <?php if ($usuario->status) echo 'checked'; ?> /> <small>Ativo</small>
			   		</label>
			   	</div>
		   </div>
	  	</div>
	</div>

    <div class="grid">
    	<div class="col-1-12">
    	   <div class="content">
    	   		<label for="Nome">Nome:</label>
    	   </div>
      	</div>
    	<div class="col-11-12">
    		<div class="content">
    			<input class="form-control" name="nome" type="text" value="<?php echo $usuario->nome; ?>" autofocus="autofocus" />
    		</div>
    	</div>
    </div>
    
    <div class="grid">
    	<div class="col-1-12">
    	   <div class="content">
    	   		<label for="Login">Login:</label>
    	   </div>
      	</div>
    	<div class="col-5-12">
    		<div class="content">
    			<input class="form-control" name="login" type="text" value="<?php echo $usuario->login; ?>" />
    		</div>
    	</div>
    	<div class="col-1-12">
    	   <div class="content">
    	   		<label for="Senha">Senha:</label>
    	   </div>
    		</div>
    	<div class="col-5-12">
    		<div class="content">
    			<input class="form-control" name="senha" type="password" />
    		</div>
    	</div>
    </div>
    
    <div class="grid">
    	<div class="col-1-12">
    	   <div class="content">
    	   		<label for="E-mail">E-mail:</label>
    	   </div>
      	</div>
    	<div class="col-5-12">
    		<div class="content">
    			<input class="form-control" name="email" type="text" value="<?php echo $usuario->email; ?>" />
    		</div>
    	</div>
    	<div class="col-1-12">
    	   <div class="content">
    	   		<label for="Permissão">Permissão:</label>
    	   </div>
    	</div>
    	<div class="col-5-12">
    		<div class="content">
    			<select class="form-control" name="permissao">
    				<option value="">--Selecione--</option>
    				<?php
    					foreach ($params['permissoes'] as $permissao) {
    						echo '<option';
    						if($usuario->permissao == $permissao->id) {
    							echo ' selected';
    						}
    						echo ' value="' . $permissao->id . '">';
    						echo $permissao->nome;
    						echo '</option>';
    					}
    				?>
    			</select>
    		</div>
    	</div>
    </div>

    <div class="grid">
    	<div class="col-1-12">
    		<div class="content">
    			&nbsp;
    		</div>
    	</div>
		<div class="col-11-12">
		   <div class="content">
		   		<input type="hidden" name="filtrar" value="0" />
			   	<div class="checkbox">
			   		<label>
						<input type="checkbox" name="filtrar" value="1" <?php if ($usuario->filtrar) echo 'checked'; ?> /> <small>Usuário só pode ver as pré-inscrições realizadas por ele</small>
			   		</label>
			   	</div>
                <input type="hidden" name="representante" value="0" />
                <div class="checkbox">
                    <label>
                        <input type="checkbox" name="representante" value="1" <?php if ($usuario->representante) echo 'checked'; ?> /> <small>Atribuir função de representante</small>
                    </label>
                </div>
		   </div>
	  	</div>
	</div>

	<input class="btn btn-default" type="submit" value="Salvar" /> 

</form>