<?php foreach($params['objetos'] as $key => $objeto) { ?>
<tr id="tr<?php echo $objeto->id; ?>">
  <th scope="row">
    <small><?php echo $inicio++; ?></small>
  </th>
  <td>
    <input type="checkbox" name="objetos[]" value="<?php echo $objeto->id; ?>">
  </td>
  <td>
    <a<?php if ($objeto->status == 0) echo ' class="desativada"'; ?> href="?modulo=<?php echo $modulo; ?>&acao=cadastrar&id=<?php echo $objeto->id; ?>"><?php echo $objeto->nome; ?></a>
  </td>
  <td class="center"><?php echo $objeto->email; ?></td>
  <td class="center"><?php echo $objeto->nomePermissao; ?></td>
  <td class="center"><?php echo Funcoes::soData($objeto->data); ?></td>
  <td align="center">
    <a class="excluir-click" target="_self" 
      href="?modulo=<?php echo $modulo; ?>&acao=excluir&id=<?php echo $objeto->id; ?>">Excluir</a>
  </td>
</tr>
<tr class="links">
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td colspan="5">
    <div id="links">
      <a target="_self" href="?modulo=<?php echo $modulo; ?>&acao=acessar&id=<?php echo $objeto->id; ?>">Acessar como</a> |
      <a target="_self" href="?modulo=<?php echo $modulo; ?>&acao=unidades&id=<?php echo $objeto->id; ?>">Unidades</a> |
      <a target="_self" href="?modulo=<?php echo $modulo; ?>&acao=cursos&id=<?php echo $objeto->id; ?>">Cursos</a>
    </div>
  </td>
</tr>
<?php } ?>
