<?php
	$params = $this->getParams();
    $conteudo = $params["conteudo"];
?>

<div class="grid top-items">
	<div class="col-1-1">
		<div class="content">
			<span id="carregar">
				<a href="?modulo=academico&acao=carregar">Carregar outro arquivo</a>
			</span>
		</div>
	</div>
</div>

<p class="destaque small">Verifique no sistema acadêmico as informações dos alunos relacionados abaixo nas disciplinas apresentadas. O sistema detectou registros com informações duplicadas de frequências e notas para uma mesma disciplina. Para visualizar o conteúdo do arquivo texto enviado clique <a href="?modulo=academico&acao=ler&file=<?php echo $_GET['file']; ?>"><u>aqui</u></a></p>

<table style="font-size:0.7em; width: 100%;">
<thead style="text-align: left;">
	<th></th>
	<th align="center">Código</th>
	<th>Curso</th>
	<th>CPF</th>
	<th>Nome</th>
	<th>Disciplina</th>
	<th align="center">Nota</th>
	<th align="center">Faltas</th>
	<th align="center">Situação</th>
	<th class="center">Data Fim Curso</th>
	<th class="center">Nota Substituída</th>
	<th class="center">Data Reposição</th>
</thead>
<tbody>
<?php
$linha = true;
foreach ($conteudo as $key => $value) {
	
	list($codigoAluno, $numSeqAluno, $nomeAluno, $dataMatAluno, $situacaoAluno, $codigoCurso, $nomeCurso, $nomeDisciplina, $cargaHorDisciplina, $notaAluno, $situacaoNota, $numeroFaltas, $notaTrabalho, $periodoRelatorio, $email, $cpf, $dataFimCurso, $notaSubstituida, $dataReposicao, 
		$obsReposicao) = array_pad(explode(";", $value),20,NULL);
	
	echo '<tr';
	if ($linha) {
		 echo ' style="background-color:#f4f0f0;" class="linha"';
	}
	echo '>';
	echo '<td><small>' . (++$key) . '</small></td>';
	
	echo '<td align="center">';
	echo $codigoCurso;
	echo '</td>';
	
	echo '<td>';
	list(,$nomeCurso) = explode(" - ", $nomeCurso);
	echo utf8_encode($nomeCurso);
	echo '</td>';
	
	echo '<td>';
	echo $cpf;
	echo '</td>';
	
	echo '<td>';
	list(,$nomeAluno) = explode(" - ", $nomeAluno);
	echo utf8_encode($nomeAluno);
	echo '</td>';
	
	echo '<td>';
	echo utf8_encode($nomeDisciplina);
	echo '</td>';
	
	echo '<td align="center">';
	echo $notaAluno;
	echo '</td>';
	
	echo '<td align="center">';
	echo $numeroFaltas;
	echo '</td>';
	
	echo '<td align="center">';
	echo $situacaoNota;
	echo '</td>';

	echo '<td class="center">';
	echo $dataFimCurso;
	echo '</td>';

	echo '<td class="center">';
	echo $notaSubstituida;
	echo '</td>';

	echo '<td class="center">';
	echo $dataReposicao;
	echo '</td>';
	
	$linha = !$linha;
	echo '</tr>';
}
?>
</tbody>
</table>

<div class="grid top-items">
	<div class="col-1-1">
		<div class="content">
			<span id="carregar">
				<a href="?modulo=academico&acao=carregar">Carregar outro arquivo</a>
			</span>
		</div>
	</div>
</div>