<?php foreach($params['objetos'] as $key => $objeto) { ?>
<tr id="tr<?php echo $objeto->id; ?>">
  <th scope="row">
    <small><?php echo $inicio++; ?></small>
  </th>
  <td>
    <input type="checkbox" name="objetos[]" value="<?php echo $objeto->id; ?>">
  </td>
  <td>
    <a href="?modulo=<?php echo $modulo; ?>&acao=cadastrar2&id=<?php echo $objeto->id; ?>"><?php echo $objeto->cpf; ?></a>
  </td>
  <td><?php echo $objeto->email; ?></td>
  <td class="center"><?php echo Funcoes::soData($objeto->data); ?></td>
  <td align="center">
    <a class="excluir-click" target="_self" 
      href="?modulo=<?php echo $modulo; ?>&acao=excluir2&id=<?php echo $objeto->id; ?>">Excluir</a>
  </td>
</tr>
<?php } ?>
