<style>
	#mensagem {
		margin-left: 34%;
		width: 30%;
	}
	input {
		margin-bottom: 10px;
	}
</style>

<form method="post">
	<div class="grid">
		<div class="col-4-12">
			<div class="content">
				&nbsp;
			</div>
		</div>
		<div class="col-4-12">
			<div class="content">	
		      <input type="text" class="form-control" name="login" placeholder="Login" required="" autofocus="" />
		      <input type="password" class="form-control" name="senha" placeholder="Senha" required=""/>
		      <input class="btn btn-default" type="submit" value="Login">   
			</div>
		</div>
		<div class="col-4-12">
			<div class="content">
				&nbsp;
			</div>
		</div>
	</div>
</form>