<?php foreach($params['objetos'] as $key => $objeto) { ?>
<tr id="tr<?php echo $objeto->id; ?>">
  <th scope="row">
    <small><?php echo $inicio++; ?></small>
  </th>
  <td>
    <input type="checkbox" name="objetos[]" value="<?php echo $objeto->id; ?>">
  </td>
  <td class="center"><?php echo Log::getOnde($objeto->onde); ?></td>
  <td>
    <a href="?modulo=<?php echo $modulo; ?>&acao=cadastrar&id=<?php echo $objeto->id; ?>"><?php echo $objeto->quem; ?></a>
  </td>
  <td class="center"><?php echo $objeto->acao; ?></td>
  <td class="center"><?php echo $objeto->oque; ?></td>
  <td class="center"><?php echo $objeto->qual; ?></td>
  <td><?php echo $objeto->descricao; ?></td>
  <td class="center"><?php echo Funcoes::getFromTimestamp($objeto->timestamp); ?></td>
  <td class="center"><?php echo Funcoes::getFromTimestamp($objeto->timestamp, 'H:i'); ?></td>
  <td align="center">
    <a class="excluir-click" target="_self" 
      href="?modulo=<?php echo $modulo; ?>&acao=excluir&id=<?php echo $objeto->id; ?>">Excluir</a>
  </td>
</tr>
<?php } ?>
