<?php foreach($params['objetos'] as $key => $objeto) { ?>
<tr id="tr<?php echo $objeto->id; ?>">
  <th scope="row">
    <small><?php echo $inicio++; ?></small>
  </th>
  <td>
    <input type="checkbox" name="objetos[]" value="<?php echo $objeto->id; ?>">
  </td>
  <td>
    <a href="?modulo=<?php echo $modulo; ?>&acao=cadastrar&id=<?php echo $objeto->id; ?>"><?php echo $objeto->nome; ?></a><br />
    <small><?php echo Ligar::getSituacao($objeto->situacao); ?></small>
  </td>
  <?php 
    $classes = array();
    $classes[] = 'center';
    if ($objeto->convertido) {
      $classes[] = 'tooltp right';
    }
  ?>
  <td class="<?php echo implode(' ', $classes); ?>"><?php 
      if ($objeto->convertido) {
        echo '<span>Sim</span>';
        echo '<div class="tip right">' . $objeto->curso . '</div>';
      } 
      else {
        echo 'Não'; 
      }?></td>
  <td class="center"><?php echo $objeto->horario; ?></td>
  <td class="center"><?php echo $objeto->operadora; ?></td>
  <td class="center"><?php echo $objeto->telefone; ?></td>
  <td class="center"><?php echo $objeto->whatsapp ? 'Sim' : 'Não'; ?></td>
  <td class="tooltp left">
    <span><?php echo Funcoes::compactaTexto($objeto->assunto, 10); ?></span>
    <?php if(!empty($objeto->assunto)) { ?>
    <div class="tip left"><?php echo $objeto->assunto; ?></div>
    <?php } ?>
  </td>
  <td class="tooltp left">
    <span><?php echo Funcoes::compactaTexto($objeto->cursos, 10); ?></span>
    <?php if(!empty($objeto->cursos)) { ?>
    <div class="tip left"><?php echo $objeto->cursos; ?></div>
    <?php } ?>
  </td>
  <td class="center"><?php echo $objeto->cidade; ?></td>
  <td class="tooltp left">
    <span><?php echo Funcoes::compactaTexto($objeto->observacoes, 10); ?></span>
    <?php if(!empty($objeto->observacoes)) { ?>
    <div class="tip left"><?php echo $objeto->observacoes; ?></div>
    <?php } ?>
  </td>
  <td class="center"><?php echo Funcoes::soData($objeto->data); ?></td>
  <td align="center">
    <a class="excluir-click" target="_self" 
      href="?modulo=<?php echo $modulo; ?>&acao=excluir&id=<?php echo $objeto->id; ?>">Excluir</a>
  </td>
</tr>
<tr class="links">
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td colspan="12">
    <?php if (!$objeto->convertido) { ?>
    <div id="links">
      <a target="_self" href="?modulo=<?php echo $modulo; ?>&acao=nova&id=<?php echo $objeto->id; ?>">Converter para inscrição</a>
    </div>
    <?php } ?>
  </td>
</tr>
<?php } ?>
